version: '3.8'

services:
  env:
    container_name: Atcoder
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: "16gb"
    volumes:
      - type: bind
        source: ./
        target: /workspace
    working_dir: /workspace
    tty: true
    environment:
      - PYTHONPATH=/workspace
